# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-05 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_1', models.CharField(max_length=200)),
                ('year_2', models.CharField(max_length=200)),
                ('year_3', models.CharField(max_length=200)),
                ('year_4', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fin_Statements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_type', models.CharField(max_length=200)),
                ('line_item', models.CharField(max_length=200)),
                ('year_1_val', models.BigIntegerField()),
                ('year_2_val', models.BigIntegerField()),
                ('year_3_val', models.BigIntegerField()),
                ('year_4_val', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Summary_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.DecimalField(decimal_places=2, max_digits=7)),
                ('year_high', models.DecimalField(decimal_places=2, max_digits=7)),
                ('year_low', models.DecimalField(decimal_places=2, max_digits=7)),
                ('beta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('market_cap', models.BigIntegerField()),
                ('previous_close', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quick_search.Stock')),
            ],
        ),
        migrations.AddField(
            model_name='fin_statements',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quick_search.Stock'),
        ),
        migrations.AddField(
            model_name='data_dates',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quick_search.Stock'),
        ),
    ]
