# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quick_search', '0002_auto_20170306_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary_data',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
