# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-07 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_search', '0003_summary_data_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary_data',
            name='previous_close',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='summary_data',
            name='target',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='summary_data',
            name='year_high',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='summary_data',
            name='year_low',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
